---

- hosts: all
  become: yes
  tasks:
  -  name: Install zabbix-agent on RedHat Family
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        zabbix-agent systemd
  -  name: Install script on RedHat
     template:
        src: /etc/ansible/common/files/zabbixcent
        dest: /etc/zabbix/zabbix_agentd.conf
        mode: 0777
     when:
        ansible_os_family == "RedHat"
  -  name: Install zabbix-agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd
  -  name: Install script on Debian
     template:
        src: /etc/ansible/common/files/zabbixubun
        dest: /etc/zabbix/zabbix_agentd.conf
        mode: 0777
     when:
        ansible_os_family == "Debian"
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
